/* tslint:disable */
/* eslint-disable */
/**
 * Task scheduling system
 * Task scheduling system
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomRegister
 */
export interface CustomRegister {
    /**
     * 
     * @type {string}
     * @memberof CustomRegister
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof CustomRegister
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CustomRegister
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof CustomRegister
     */
    retypedPassword: string;
}

/**
 * Check if a given object implements the CustomRegister interface.
 */
export function instanceOfCustomRegister(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "retypedPassword" in value;

    return isInstance;
}

export function CustomRegisterFromJSON(json: any): CustomRegister {
    return CustomRegisterFromJSONTyped(json, false);
}

export function CustomRegisterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomRegister {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'email': json['email'],
        'password': json['password'],
        'retypedPassword': json['retyped_password'],
    };
}

export function CustomRegisterToJSON(value?: CustomRegister | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'email': value.email,
        'password': value.password,
        'retyped_password': value.retypedPassword,
    };
}

