/* tslint:disable */
/* eslint-disable */
/**
 * Task scheduling system
 * Task scheduling system
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomUser
 */
export interface CustomUser {
    /**
     * 
     * @type {number}
     * @memberof CustomUser
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof CustomUser
     */
    readonly lastLogin: Date | null;
    /**
     * Designates that this user has all permissions without explicitly assigning them.
     * @type {boolean}
     * @memberof CustomUser
     */
    isSuperuser?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     * @type {boolean}
     * @memberof CustomUser
     */
    isStaff?: boolean;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     * @type {boolean}
     * @memberof CustomUser
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CustomUser
     */
    readonly dateJoined: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomUser
     */
    readonly email: string;
    /**
     * 
     * @type {string}
     * @memberof CustomUser
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof CustomUser
     */
    username: string;
    /**
     * The groups this user belongs to. A user will get all permissions granted to each of their groups.
     * @type {Array<number>}
     * @memberof CustomUser
     */
    groups?: Array<number>;
    /**
     * Specific permissions for this user.
     * @type {Array<number>}
     * @memberof CustomUser
     */
    userPermissions?: Array<number>;
}

/**
 * Check if a given object implements the CustomUser interface.
 */
export function instanceOfCustomUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "lastLogin" in value;
    isInstance = isInstance && "dateJoined" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "fullName" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function CustomUserFromJSON(json: any): CustomUser {
    return CustomUserFromJSONTyped(json, false);
}

export function CustomUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'lastLogin': (json['last_login'] === null ? null : new Date(json['last_login'])),
        'isSuperuser': !exists(json, 'is_superuser') ? undefined : json['is_superuser'],
        'isStaff': !exists(json, 'is_staff') ? undefined : json['is_staff'],
        'isActive': !exists(json, 'is_active') ? undefined : json['is_active'],
        'dateJoined': (new Date(json['date_joined'])),
        'email': json['email'],
        'fullName': json['full_name'],
        'username': json['username'],
        'groups': !exists(json, 'groups') ? undefined : json['groups'],
        'userPermissions': !exists(json, 'user_permissions') ? undefined : json['user_permissions'],
    };
}

export function CustomUserToJSON(value?: CustomUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'is_superuser': value.isSuperuser,
        'is_staff': value.isStaff,
        'is_active': value.isActive,
        'full_name': value.fullName,
        'username': value.username,
        'groups': value.groups,
        'user_permissions': value.userPermissions,
    };
}

