/* tslint:disable */
/* eslint-disable */
/**
 * Task scheduling system
 * Task scheduling system
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Task } from './Task';
import {
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
} from './Task';

/**
 * 
 * @export
 * @interface PaginatedTaskList
 */
export interface PaginatedTaskList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTaskList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTaskList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTaskList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Task>}
     * @memberof PaginatedTaskList
     */
    results?: Array<Task>;
}

/**
 * Check if a given object implements the PaginatedTaskList interface.
 */
export function instanceOfPaginatedTaskList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedTaskListFromJSON(json: any): PaginatedTaskList {
    return PaginatedTaskListFromJSONTyped(json, false);
}

export function PaginatedTaskListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTaskList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(TaskFromJSON)),
    };
}

export function PaginatedTaskListToJSON(value?: PaginatedTaskList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(TaskToJSON)),
    };
}

