/* tslint:disable */
/* eslint-disable */
/**
 * Task scheduling system
 * Task scheduling system
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CustomUser } from './CustomUser';
import {
    CustomUserFromJSON,
    CustomUserFromJSONTyped,
    CustomUserToJSON,
} from './CustomUser';

/**
 * 
 * @export
 * @interface PaginatedCustomUserList
 */
export interface PaginatedCustomUserList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCustomUserList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCustomUserList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCustomUserList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<CustomUser>}
     * @memberof PaginatedCustomUserList
     */
    results?: Array<CustomUser>;
}

/**
 * Check if a given object implements the PaginatedCustomUserList interface.
 */
export function instanceOfPaginatedCustomUserList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedCustomUserListFromJSON(json: any): PaginatedCustomUserList {
    return PaginatedCustomUserListFromJSONTyped(json, false);
}

export function PaginatedCustomUserListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCustomUserList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(CustomUserFromJSON)),
    };
}

export function PaginatedCustomUserListToJSON(value?: PaginatedCustomUserList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(CustomUserToJSON)),
    };
}

