/* tslint:disable */
/* eslint-disable */
/**
 * Task scheduling system
 * Task scheduling system
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SocialAccount } from './SocialAccount';
import {
    SocialAccountFromJSON,
    SocialAccountFromJSONTyped,
    SocialAccountToJSON,
} from './SocialAccount';

/**
 * 
 * @export
 * @interface PaginatedSocialAccountList
 */
export interface PaginatedSocialAccountList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSocialAccountList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSocialAccountList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSocialAccountList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<SocialAccount>}
     * @memberof PaginatedSocialAccountList
     */
    results?: Array<SocialAccount>;
}

/**
 * Check if a given object implements the PaginatedSocialAccountList interface.
 */
export function instanceOfPaginatedSocialAccountList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedSocialAccountListFromJSON(json: any): PaginatedSocialAccountList {
    return PaginatedSocialAccountListFromJSONTyped(json, false);
}

export function PaginatedSocialAccountListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSocialAccountList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(SocialAccountFromJSON)),
    };
}

export function PaginatedSocialAccountListToJSON(value?: PaginatedSocialAccountList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(SocialAccountToJSON)),
    };
}

