/* tslint:disable */
/* eslint-disable */
/**
 * Task scheduling system
 * Task scheduling system
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `0` - Thap
 * * `1` - Trung binh
 * * `2` - Cao
 * @export
 */
export const PriorityEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type PriorityEnum = typeof PriorityEnum[keyof typeof PriorityEnum];


export function PriorityEnumFromJSON(json: any): PriorityEnum {
    return PriorityEnumFromJSONTyped(json, false);
}

export function PriorityEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriorityEnum {
    return json as PriorityEnum;
}

export function PriorityEnumToJSON(value?: PriorityEnum | null): any {
    return value as any;
}

