/* tslint:disable */
/* eslint-disable */
/**
 * Task scheduling system
 * Task scheduling system
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `github` - GitHub
 * * `google` - Google
 * @export
 */
export const ProviderEnum = {
    Github: 'github',
    Google: 'google'
} as const;
export type ProviderEnum = typeof ProviderEnum[keyof typeof ProviderEnum];


export function ProviderEnumFromJSON(json: any): ProviderEnum {
    return ProviderEnumFromJSONTyped(json, false);
}

export function ProviderEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderEnum {
    return json as ProviderEnum;
}

export function ProviderEnumToJSON(value?: ProviderEnum | null): any {
    return value as any;
}

