/* tslint:disable */
/* eslint-disable */
/**
 * Task scheduling system
 * Task scheduling system
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SocialConnect
 */
export interface SocialConnect {
    /**
     * 
     * @type {string}
     * @memberof SocialConnect
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialConnect
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialConnect
     */
    idToken?: string;
}

/**
 * Check if a given object implements the SocialConnect interface.
 */
export function instanceOfSocialConnect(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SocialConnectFromJSON(json: any): SocialConnect {
    return SocialConnectFromJSONTyped(json, false);
}

export function SocialConnectFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialConnect {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'access_token') ? undefined : json['access_token'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'idToken': !exists(json, 'id_token') ? undefined : json['id_token'],
    };
}

export function SocialConnectToJSON(value?: SocialConnect | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
        'code': value.code,
        'id_token': value.idToken,
    };
}

