/* tslint:disable */
/* eslint-disable */
/**
 * Task scheduling system
 * Task scheduling system
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PriorityEnum } from './PriorityEnum';
import {
    PriorityEnumFromJSON,
    PriorityEnumFromJSONTyped,
    PriorityEnumToJSON,
} from './PriorityEnum';
import type { StatusEnum } from './StatusEnum';
import {
    StatusEnumFromJSON,
    StatusEnumFromJSONTyped,
    StatusEnumToJSON,
} from './StatusEnum';

/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof Task
     */
    startTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Task
     */
    endTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Task
     */
    plannedTime?: Date | null;
    /**
     * 
     * @type {StatusEnum}
     * @memberof Task
     */
    status?: StatusEnum;
    /**
     * 
     * @type {PriorityEnum}
     * @memberof Task
     */
    priority?: PriorityEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Task
     */
    toDo?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Task
     */
    readonly createdTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof Task
     */
    readonly modifiedTime: Date;
}

/**
 * Check if a given object implements the Task interface.
 */
export function instanceOfTask(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "createdTime" in value;
    isInstance = isInstance && "modifiedTime" in value;

    return isInstance;
}

export function TaskFromJSON(json: any): Task {
    return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'startTime': !exists(json, 'start_time') ? undefined : (json['start_time'] === null ? null : new Date(json['start_time'])),
        'endTime': !exists(json, 'end_time') ? undefined : (json['end_time'] === null ? null : new Date(json['end_time'])),
        'plannedTime': !exists(json, 'planned_time') ? undefined : (json['planned_time'] === null ? null : new Date(json['planned_time'])),
        'status': !exists(json, 'status') ? undefined : StatusEnumFromJSON(json['status']),
        'priority': !exists(json, 'priority') ? undefined : PriorityEnumFromJSON(json['priority']),
        'toDo': !exists(json, 'to_do') ? undefined : json['to_do'],
        'createdTime': (new Date(json['created_time'])),
        'modifiedTime': (new Date(json['modified_time'])),
    };
}

export function TaskToJSON(value?: Task | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'start_time': value.startTime === undefined ? undefined : (value.startTime === null ? null : value.startTime.toISOString()),
        'end_time': value.endTime === undefined ? undefined : (value.endTime === null ? null : value.endTime.toISOString()),
        'planned_time': value.plannedTime === undefined ? undefined : (value.plannedTime === null ? null : value.plannedTime.toISOString()),
        'status': StatusEnumToJSON(value.status),
        'priority': PriorityEnumToJSON(value.priority),
        'to_do': value.toDo,
    };
}

